services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Netresearch\NrcUniversalMessenger\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    Netresearch\NrcUniversalMessenger\Command\ImportCommand:
        tags:
            - name: 'console.command'
              command: 'universal-messenger:newsletter-channels:import'
              description: 'Imports all active Universal Messenger newsletter channels'
              schedulable: true

    Netresearch\NrcUniversalMessenger\EventListener\ModifyPageLayoutContentEventListener:
        tags:
            - name: event.listener
              event: TYPO3\CMS\Backend\Controller\Event\ModifyPageLayoutContentEvent

    Netresearch\NrcUniversalMessenger\Controller\UniversalMessengerController:
        tags: [ 'backend.controller' ]
